# Project 2 - Air Barcelona

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Import the data set
#We realized when you import the cvs file without doing anything, not all missing values may be read as NaN
    #Thereforethe number of NaN values can't be displayed correctly and the data can't be cleaned/filled completely
    #To solve this problem, re-import the csv file and apply pd.("...",na_values = missing_values) to read_csv

missing_values = ["n/a", "na", "--"]
air_quality = pd.read_csv(r"C:\Users\kim.buchner\Desktop\Ironhack\Module1\WEEK2\Project-Week-2-Barcelona\datasets\2.-Urban-Environment\air-quality-nov-2017.csv", na_values = missing_values)

### Information about dataset

In [3]:
air_quality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5744 entries, 0 to 5743
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Station       5744 non-null   object
 1   Air Quality   5583 non-null   object
 2   Longitude     5744 non-null   float64
 3   Latitude      5744 non-null   float64
 4   O3 Hour       4268 non-null   object
 5   O3 Quality    4101 non-null   object
 6   O3 Value      4101 non-null   float64
 7   NO2 Hour      5689 non-null   object
 8   NO2 Quality   5460 non-null   object
 9   NO2 Value     5460 non-null   float64
 10  PM10 Hour     3722 non-null   object
 11  PM10 Quality  3647 non-null   object
 12  PM10 Value    3647 non-null   float64
 13  Generated     5744 non-null   object
 14  Date Time     5744 non-null   int64
dtypes: float64(5), int64(1), object(9)
memory usage: 673.2+ KB

## Raw data

In [4]:
air_quality.iloc[0:15]

,Station,Air Quality,Longitude,Latitude,O3 Hour,O3 Quality,O3 Value,NO2 Hour,NO2 Quality,NO2 Value,PM10 Hour,PM10 Quality,PM10 Value,Generated,Date Time
0,Barcelona - Sants,Good,2.1331,41.3788,NaN,NaN,NaN,0h,Good,84.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
1,Barcelona - Eixample,Moderate,2.1538,41.3853,0h,Good,1.0,0h,Moderate,113.0,0h,Good,36.0,01/11/2018 0:00,1541027104
2,Barcelona - Gràcia,Good,2.1534,41.3987,0h,Good,10.0,0h,Good,73.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
3,Barcelona - Ciutadella,Good,2.1874,41.3864,0h,Good,2.0,0h,Good,86.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
4,Barcelona - Vall Hebron,Good,2.1480,41.4261,0h,Good,7.0,0h,Good,69.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
5,Barcelona - Palau Reial,Good,2.1151,41.3875,23h,Good,11.0,23h,Good,57.0,23h,Good,23.0,01/11/2018 0:00,1541027104
6,Barcelona - Poblenou,Good,2.2045,41.4039,NaN,NaN,NaN,23h,Good,86.0,23h,Good,32.0,01/11/2018 0:00,1541027104
7,Barcelona - Observ Fabra,Good,2.1239,41.4183,23h,Good,58.0,23h,Good,3.0,23h,Good,25.0,01/11/2018 0:00,1541027104
8,Barcelona - Sants,Good,2.1331,41.3788,NaN,NaN,NaN,0h,Good,62.0,NaN,NaN,NaN,01/11/2018 1:00,1541030725
9,Barcelona - Eixample,Good,2.1538,41.3853,0h,Good,6.0,0h,Good,80.0,1h,Good,35.0,01/11/2018 1:00,1541030725
10,Barcelona - Gràcia,Good,2.1534,41.3987,0h,Good,21.0,0h,Good,59.0,NaN,NaN,NaN,01/11/2018 1:00,1541030725
11,Barcelona - Ciutadella,Good,2.1874,41.3864,0h,Good,4.0,0h,Good,78.0,NaN,NaN,NaN,01/11/2018 1:00,1541030725
12,Barcelona - Vall Hebron,Good,2.1480,41.4261,0h,Good,29.0,0h,Good,45.0,NaN,NaN,NaN,01/11/2018 1:00,1541030725
13,Barcelona - Palau Reial,Good,2.1151,41.3875,0h,Good,27.0,0h,Good,38.0,1h,Good,24.0,01/11/2018 1:00,1541030725
14,Barcelona - Poblenou,Good,2.2045,41.4039,NaN,NaN,NaN,0h,Good,75.0,1h,Good,32.0,01/11/2018 1:00,1541030725

### Null values in data

In [5]:
air_quality.isnull().sum()

Station            0
Air Quality      161
Longitude          0
Latitude           0
O3 Hour         1476
O3 Quality      1643
O3 Value        1643
NO2 Hour          55
NO2 Quality      284
NO2 Value        284
PM10 Hour       2022
PM10 Quality    2097
PM10 Value      2097
Generated          0
Date Time          0
dtype: int64

In [6]:
air_quality.isnull().sum().sum()

11762

### Data Cleaning

In [7]:
#Decision on Data Cleaning

#Rename / add "µg/m3" in columns missing units (like NO2 Value) > DONE

#First display null values and think which replacement makes sense for null values
    #Display columns with null values to see whats going on
    
#Also how to replace the null values (Tim: use column "Generated" to fill null values in 03/NO2/PM10 Hour)
   #Ideas to fill these missing values
    #Date Time = sample number of all stations measurements in one hour/day
    #Use values of days before, of the same station, same pollutant (if possible) to fill the missing values
    
#Split up column Generated into 2, x for time generated and y for date generated and remove Generated

#Remove column Generated
#Remove columns Longi/Latitude, since we see no possible use for this data as we already have a location of the measurment taken
#Change column Station to BCN Stations and remove "Barcelona - " in the beginning of the values 

#Check for duplicates in partly cleaned dataframe and remove (none found)

#Remove -- in column, not shown as null value (see solution in first cell)

# DATA CLEANING STRUCTURE 

#For the columns x-Value possibly use median of dataset to fill null values !!!!!!!!!!!!!
    #No, because at closer look (see bottom) data revealed to be completely missing for several pollutants and stations
    #Complete data at 3 stations (code missing)
        #Make a subdata with just the 3 stations and apply research to answer questions
        #After researching on subdata go and check for other ways to use rest of dataset
        #Either use other data sources or (if possible, not sure at the moment) use existing data of x-Value to create "trend"
    
#For columns x-Hour missing values    
     #Date Time = sample number of all stations measurements in one hour/day
     #Use values of days before, of the same station, same pollutant (if possible) to fill the missing values

In [8]:
#Displaying only the pollutants to get an overview
air_quality[["O3 Quality","O3 Value","NO2 Quality","NO2 Value","PM10 Quality","PM10 Value"]].head(9)

  O3 Quality  O3 Value NO2 Quality  NO2 Value PM10 Quality  PM10 Value
0        NaN       NaN        Good       84.0          NaN         NaN
1       Good       1.0    Moderate      113.0         Good        36.0
2       Good      10.0        Good       73.0          NaN         NaN
3       Good       2.0        Good       86.0          NaN         NaN
4       Good       7.0        Good       69.0          NaN         NaN
5       Good      11.0        Good       57.0         Good        23.0
6        NaN       NaN        Good       86.0         Good        32.0
7       Good      58.0        Good        3.0         Good        25.0
8        NaN       NaN        Good       62.0          NaN         NaN

In [9]:
#Add the unit to the columns names of the polutants
air_quality = air_quality.rename(columns={"O3 Value":"O3 µg/m3","NO2 Value":"NO2 µg/m3","PM10 Value":"PM10 µg/m3"})
air_quality

,Station,Air Quality,Longitude,Latitude,O3 Hour,O3 Quality,O3 µg/m3,NO2 Hour,NO2 Quality,NO2 µg/m3,PM10 Hour,PM10 Quality,PM10 µg/m3,Generated,Date Time
0,Barcelona - Sants,Good,2.1331,41.3788,NaN,NaN,NaN,0h,Good,84.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
1,Barcelona - Eixample,Moderate,2.1538,41.3853,0h,Good,1.0,0h,Moderate,113.0,0h,Good,36.0,01/11/2018 0:00,1541027104
2,Barcelona - Gràcia,Good,2.1534,41.3987,0h,Good,10.0,0h,Good,73.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
3,Barcelona - Ciutadella,Good,2.1874,41.3864,0h,Good,2.0,0h,Good,86.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
4,Barcelona - Vall Hebron,Good,2.1480,41.4261,0h,Good,7.0,0h,Good,69.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5739,Barcelona - Ciutadella,Good,2.1874,41.3864,22h,Good,10.0,22h,Good,57.0,NaN,NaN,NaN,30/11/2018 23:00,1543615502
5740,Barcelona - Vall Hebron,Good,2.1480,41.4261,22h,Good,32.0,22h,Good,31.0,22h,Good,21.0,30/11/2018 23:00,1543615502
5741,Barcelona - Palau Reial,Good,2.1151,41.3875,22h,Good,40.0,22h,Good,20.0,22h,Good,15.0,30/11/2018 23:00,1543615502
5742,Barcelona - Poblenou,Good,2.2045,41.4039,NaN,NaN,NaN,22h,Good,70.0,22h,Good,25.0,30/11/2018 23:00,1543615502
5743,Barcelona - Observ Fabra,Good,2.1239,41.4183,22h,Good,64.0,22h,Good,21.0,22h,Good,12.0,30/11/2018 23:00,1543615502

In [10]:
#Split Generated into 2 columns 'Generated Date','Generated Time'
air_quality[['Generated Date','Generated Time']] = air_quality.Generated.str.split(expand=True)
air_quality

,Station,Air Quality,Longitude,Latitude,O3 Hour,O3 Quality,O3 µg/m3,NO2 Hour,NO2 Quality,NO2 µg/m3,PM10 Hour,PM10 Quality,PM10 µg/m3,Generated,Date Time,Generated Date,Generated Time
0,Barcelona - Sants,Good,2.1331,41.3788,NaN,NaN,NaN,0h,Good,84.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104,01/11/2018,0:00
1,Barcelona - Eixample,Moderate,2.1538,41.3853,0h,Good,1.0,0h,Moderate,113.0,0h,Good,36.0,01/11/2018 0:00,1541027104,01/11/2018,0:00
2,Barcelona - Gràcia,Good,2.1534,41.3987,0h,Good,10.0,0h,Good,73.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104,01/11/2018,0:00
3,Barcelona - Ciutadella,Good,2.1874,41.3864,0h,Good,2.0,0h,Good,86.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104,01/11/2018,0:00
4,Barcelona - Vall Hebron,Good,2.1480,41.4261,0h,Good,7.0,0h,Good,69.0,NaN,NaN,NaN,01/11/2018 0:00,1541027104,01/11/2018,0:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5739,Barcelona - Ciutadella,Good,2.1874,41.3864,22h,Good,10.0,22h,Good,57.0,NaN,NaN,NaN,30/11/2018 23:00,1543615502,30/11/2018,23:00
5740,Barcelona - Vall Hebron,Good,2.1480,41.4261,22h,Good,32.0,22h,Good,31.0,22h,Good,21.0,30/11/2018 23:00,1543615502,30/11/2018,23:00
5741,Barcelona - Palau Reial,Good,2.1151,41.3875,22h,Good,40.0,22h,Good,20.0,22h,Good,15.0,30/11/2018 23:00,1543615502,30/11/2018,23:00
5742,Barcelona - Poblenou,Good,2.2045,41.4039,NaN,NaN,NaN,22h,Good,70.0,22h,Good,25.0,30/11/2018 23:00,1543615502,30/11/2018,23:00
5743,Barcelona - Observ Fabra,Good,2.1239,41.4183,22h,Good,64.0,22h,Good,21.0,22h,Good,12.0,30/11/2018 23:00,1543615502,30/11/2018,23:00

In [11]:
#Remove columns "Longitude","Latitude" because we (probably) wont need them
air_quality = air_quality.drop(["Generated","Longitude","Latitude", "O3 Hour", "NO2 Hour", "PM10 Hour"], axis=1)
air_quality

,Station,Air Quality,O3 Quality,O3 µg/m3,NO2 Quality,NO2 µg/m3,PM10 Quality,PM10 µg/m3,Date Time,Generated Date,Generated Time
0,Barcelona - Sants,Good,NaN,NaN,Good,84.0,NaN,NaN,1541027104,01/11/2018,0:00
1,Barcelona - Eixample,Moderate,Good,1.0,Moderate,113.0,Good,36.0,1541027104,01/11/2018,0:00
2,Barcelona - Gràcia,Good,Good,10.0,Good,73.0,NaN,NaN,1541027104,01/11/2018,0:00
3,Barcelona - Ciutadella,Good,Good,2.0,Good,86.0,NaN,NaN,1541027104,01/11/2018,0:00
4,Barcelona - Vall Hebron,Good,Good,7.0,Good,69.0,NaN,NaN,1541027104,01/11/2018,0:00
...,...,...,...,...,...,...,...,...,...,...,...
5739,Barcelona - Ciutadella,Good,Good,10.0,Good,57.0,NaN,NaN,1543615502,30/11/2018,23:00
5740,Barcelona - Vall Hebron,Good,Good,32.0,Good,31.0,Good,21.0,1543615502,30/11/2018,23:00
5741,Barcelona - Palau Reial,Good,Good,40.0,Good,20.0,Good,15.0,1543615502,30/11/2018,23:00
5742,Barcelona - Poblenou,Good,NaN,NaN,Good,70.0,Good,25.0,1543615502,30/11/2018,23:00
5743,Barcelona - Observ Fabra,Good,Good,64.0,Good,21.0,Good,12.0,1543615502,30/11/2018,23:00

In [12]:
#Remove Barcelona - from the start of each object in column Station
air_quality["Station"] = air_quality["Station"].str.replace('Barcelona - ','')
air_quality

,Station,Air Quality,O3 Quality,O3 µg/m3,NO2 Quality,NO2 µg/m3,PM10 Quality,PM10 µg/m3,Date Time,Generated Date,Generated Time
0,Sants,Good,NaN,NaN,Good,84.0,NaN,NaN,1541027104,01/11/2018,0:00
1,Eixample,Moderate,Good,1.0,Moderate,113.0,Good,36.0,1541027104,01/11/2018,0:00
2,Gràcia,Good,Good,10.0,Good,73.0,NaN,NaN,1541027104,01/11/2018,0:00
3,Ciutadella,Good,Good,2.0,Good,86.0,NaN,NaN,1541027104,01/11/2018,0:00
4,Vall Hebron,Good,Good,7.0,Good,69.0,NaN,NaN,1541027104,01/11/2018,0:00
...,...,...,...,...,...,...,...,...,...,...,...
5739,Ciutadella,Good,Good,10.0,Good,57.0,NaN,NaN,1543615502,30/11/2018,23:00
5740,Vall Hebron,Good,Good,32.0,Good,31.0,Good,21.0,1543615502,30/11/2018,23:00
5741,Palau Reial,Good,Good,40.0,Good,20.0,Good,15.0,1543615502,30/11/2018,23:00
5742,Poblenou,Good,NaN,NaN,Good,70.0,Good,25.0,1543615502,30/11/2018,23:00
5743,Observ Fabra,Good,Good,64.0,Good,21.0,Good,12.0,1543615502,30/11/2018,23:00

In [13]:
#Transforming the column 'Generated Date' into the format of a date 
air_quality['Generated Date'] = pd.to_datetime(air_quality['Generated Date'],format='%d/%m/%Y')
air_quality["Week Day"] = air_quality["Generated Date"].dt.day_name()
air_quality['Generated Date']= air_quality['Generated Date'].dt.strftime("%d/%m/%y")

## Cleaned data so far

In [20]:
air_quality.drop_duplicates(keep=False,inplace=True)
air_quality[4300:4330]

,Station,Air Quality,O3 Quality,O3 µg/m3,NO2 Quality,NO2 µg/m3,PM10 Quality,PM10 µg/m3,Date Time,Generated Date,Generated Time,Week Day
4300,Vall Hebron,Good,Good,19.0,Good,48.0,Good,15.0,1542967502,23/11/18,11:00,Friday
4301,Palau Reial,Good,Good,1.0,Good,74.0,Good,16.0,1542967502,23/11/18,11:00,Friday
4302,Poblenou,Moderate,NaN,NaN,Good,49.0,Moderate,37.0,1542967502,23/11/18,11:00,Friday
4303,Observ Fabra,Good,Good,73.0,Good,8.0,Good,8.0,1542967502,23/11/18,11:00,Friday
4304,Sants,Good,NaN,NaN,Good,66.0,NaN,NaN,1542971101,23/11/18,12:00,Friday
4305,Eixample,Good,Good,2.0,Good,78.0,Good,27.0,1542971101,23/11/18,12:00,Friday
4306,Gràcia,Good,Good,3.0,Good,81.0,Good,18.0,1542971101,23/11/18,12:00,Friday
4307,Ciutadella,Good,Good,3.0,Good,70.0,NaN,NaN,1542971101,23/11/18,12:00,Friday
4308,Vall Hebron,Good,Good,15.0,Good,52.0,Good,15.0,1542971101,23/11/18,12:00,Friday
4309,Palau Reial,Good,Good,1.0,Good,75.0,Good,16.0,1542971101,23/11/18,12:00,Friday
4310,Poblenou,Good,NaN,NaN,Good,57.0,Good,36.0,1542971101,23/11/18,12:00,Friday
4311,Observ Fabra,Good,Good,74.0,Good,9.0,Good,9.0,1542971101,23/11/18,12:00,Friday
4312,Sants,Good,NaN,NaN,Good,63.0,NaN,NaN,1542974702,23/11/18,13:00,Friday
4313,Eixample,Good,Good,1.0,Good,80.0,Good,29.0,1542974702,23/11/18,13:00,Friday
4314,Gràcia,Good,Good,2.0,Good,81.0,Good,19.0,1542974702,23/11/18,13:00,Friday
4315,Ciutadella,Good,Good,2.0,Good,65.0,NaN,NaN,1542974702,23/11/18,13:00,Friday
4316,Vall Hebron,Good,Good,7.0,Good,56.0,Good,15.0,1542974702,23/11/18,13:00,Friday
4317,Palau Reial,Good,Good,1.0,Good,75.0,Good,16.0,1542974702,23/11/18,13:00,Friday
4318,Poblenou,Good,NaN,NaN,Good,50.0,Good,36.0,1542974702,23/11/18,13:00,Friday
4319,Observ Fabra,Good,Good,65.0,Good,13.0,Good,9.0,1542974702,23/11/18,13:00,Friday
4320,Sants,Good,NaN,NaN,Good,74.0,NaN,NaN,1542978302,23/11/18,14:00,Friday
4321,Eixample,Good,Good,2.0,Good,81.0,Good,31.0,1542978302,23/11/18,14:00,Friday
4322,Gràcia,Good,Good,2.0,Good,81.0,Good,20.0,1542978302,23/11/18,14:00,Friday
4323,Ciutadella,Good,Good,7.0,Good,62.0,NaN,NaN,1542978302,23/11/18,14:00,Friday
4324,Vall Hebron,Good,Good,14.0,Good,43.0,Good,15.0,1542978302,23/11/18,14:00,Friday
4325,Palau Reial,Good,Good,2.0,Good,59.0,Good,18.0,1542978302,23/11/18,14:00,Friday
4326,Poblenou,Good,NaN,NaN,Good,50.0,Good,36.0,1542978302,23/11/18,14:00,Friday
4327,Observ Fabra,Good,Good,75.0,Good,7.0,Good,9.0,1542978302,23/11/18,14:00,Friday
4328,Sants,Good,NaN,NaN,Good,62.0,NaN,NaN,1542981902,23/11/18,15:00,Friday
4329,Eixample,Good,Good,3.0,Good,71.0,Good,31.0,1542981902,23/11/18,15:00,Friday

In [15]:
#Replacing values 
#Null values in x-Hour: make use of number in "Generated Time" to fill missing values in Hours
                        #See "Generated Time" in relation to x-Hours (display only these columns)
                        #Filter it again by number of "Generated Time" (to get an even closer look)
                        #Final decision (eg. copy value of above, other Hour value,...)
            
            #After doing this^ we could gain interesting information about hourly values (using "Generated Time")
            
#Null values in µg/m3: replace null values using median of the data set
                       #Use the info of above to actually use the daily median to replace null values

In [16]:
#Counting the amount of different values in Date Time to see how the values might relate to other values (measure sample number)
air_quality["Date Time"].iloc[0:112].value_counts()

1541048703    8
1541073903    8
1541045102    8
1541041503    8
1541063103    8
1541066703    8
1541037902    8
1541030725    8
1541034303    8
1541059503    8
1541070303    8
1541027104    8
1541055903    8
1541052302    8
Name: Date Time, dtype: int64

In [17]:
#See mean values for each pollutant on each day or each station
daily_mean_PM = air_quality.groupby(["Generated Date","Station"])[["PM10 µg/m3"]].mean('PM10 µg/m3')
daily_mean_PM.head(8) #Right now shows one day, not several (because of .head(8))

                             PM10 µg/m3
Generated Date Station
01/11/18       Ciutadella           NaN
               Eixample       21.666667
               Gràcia               NaN
               Observ Fabra   11.208333
               Palau Reial    13.875000
               Poblenou       17.375000
               Sants                NaN
               Vall Hebron          NaN

### Creating table of number of missing values for each column/station

In [18]:
#missing values in station x variable
nan_sants=air_quality[air_quality["Station"]=="Sants"].isnull().sum()
nan_eixample=air_quality[air_quality["Station"]=='Eixample'].isnull().sum()
nan_gracia=air_quality[air_quality["Station"]=='Gràcia'].isnull().sum()
nan_ciutadella=air_quality[air_quality["Station"]=='Ciutadella'].isnull().sum()
nan_valldhebron=air_quality[air_quality["Station"]=='Vall Hebron'].isnull().sum()
nan_palaureial=air_quality[air_quality["Station"]=='Palau Reial'].isnull().sum()
nan_poblenou=air_quality[air_quality["Station"]=='Poblenou'].isnull().sum()
nan_fabra=air_quality[air_quality["Station"]=='Observ Fabra'].isnull().sum()

In [19]:
nan_x_station= [nan_sants,nan_eixample,nan_gracia,nan_ciutadella,nan_valldhebron,nan_palaureial,nan_poblenou,nan_fabra]

stations = list(air_quality["Station"].unique())

nan_matrix_x_column_x_station= pd.concat(nan_x_station, axis=1)

nan_matrix_x_column_x_station.columns=stations

nan_matrix_x_column_x_station = nan_matrix_x_column_x_station.drop("Station")
nan_matrix_x_column_x_station =nan_matrix_x_column_x_station.transpose()

nan_matrix_x_column_x_station

,Air Quality,O3 Quality,O3 µg/m3,NO2 Quality,NO2 µg/m3,PM10 Quality,PM10 µg/m3,Date Time,Generated Date,Generated Time,Week Day
Sants,47,718,718,47,47,718,718,0,0,0,0
Eixample,0,73,73,74,74,0,0,0,0,0,0
Gràcia,66,74,74,74,74,507,507,0,0,0,0
Ciutadella,17,17,17,17,17,718,718,0,0,0,0
Vall Hebron,2,7,7,7,7,73,73,0,0,0,0
Palau Reial,5,17,17,17,17,22,22,0,0,0,0
Poblenou,16,718,718,29,29,34,34,0,0,0,0
Observ Fabra,8,19,19,19,19,25,25,0,0,0,0

In [21]:
air_quality = air_quality.to_csv(r"C:\Users\kim.buchner\Desktop\Ironhack\Module1\WEEK2\Project-Week-2-Barcelona\your-project\air_quality.csv")